[package]
name = "fasttensors"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.6.1", features = ["cuda"] }
lru = "0.12.4"
once_cell = "1.20.0"
serde_json = "1.0.128"
